function [missing_initial_concs, missing_params] = identify_missing_parameters(model, replacement_number)
% Scans through a model and identifies parameters which are earmarked as
% needing to be generated by the Monte Carlo simulation. 
%   Those which need to be generated are marked by having their value set
%   to replacement_number
%


% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
%                                INITIAL CONCENTRATIONS
% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
% Fill in initial concentrations as defined by replacement_number

% preloop parameter setting
eval = false;
counter = 1;

for i = 1:model.species.length
    if model.species(i).initialAmount == replacement_number
        missing_initial_concs(counter) = i;
        counter = counter + 1;
        eval = true;
    end
end

% If eval == false at this point, no initial concentrations needed to be
% replaced. To signify this we then set the first value of the
% missing_initial_concs vector to the replacement value
if (eval == false)
    missing_initial_concs(1) = replacement_number;
end


% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
%                                PARAMETERS
% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
% Fill in values for parameters as defined by replacement_number

% preloop parameter resetting
counter = 1;
eval = false;


for i = 1:model.parameter.length
    if model.parameter(i).value == replacement_number
        missing_params(counter) = i;
        counter = counter + 1;
        eval = true;
    end
end


% If eval == false at this point, no parameters needed to be
% replaced. To signify this we then set the first value of the
% missing_initial_concs vector to the replacement value
if (eval == false)
    missing_params(1) = replacement_number;
end

end

